import fs from 'node:fs/promises';
import path from 'node:path';
import type { Match, Team } from './types.js';

export async function loadMatches(dataDir:string): Promise<Match[]> { return JSON.parse(String(await fs.readFile(path.join(dataDir,'matches.json'),'utf8'))); }
export async function loadTeams(dataDir:string): Promise<Team[]> { return JSON.parse(String(await fs.readFile(path.join(dataDir,'teams.json'),'utf8'))); }
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const groups='ABCDEFGHIJKL'.split('');
const colors=['#00d4ff','#7c3aed','#22c55e','#f97316','#e11d48','#facc15','#14b8a6','#a855f7','#38bdf8','#fb7185','#84cc16','#f59e0b'];
const teamLabel=(m:Match,side:1|2)=> side===1 ? (m.team1Code ?? m.slot1 ?? 'TBD') : (m.team2Code ?? m.slot2 ?? 'TBD');
const teamName=(m:Match,side:1|2)=> side===1 ? (m.team1Name ?? m.slot1 ?? 'TBD') : (m.team2Name ?? m.slot2 ?? 'TBD');

export function renderHtml(matches: Match[], teams: Team[]) {
  const groupCards = groups.map((g,i)=>renderGroupHtml(g,i,matches,teams)).join('');
  const bracket = ['Round of 32','Round of 16','Quarter-final','Semi-final','Bronze Final','Final'].map(stage=>`<section class="round"><h3>${stage}</h3>${matches.filter(m=>m.stage===stage).map(renderKoHtml).join('')}</section>`).join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>World Cup 2026 Schedule - Aruba Time</title><style>${css()}</style></head><body><main class="poster"><header><div><p class="eyebrow">FIFA World Cup 2026</p><h1>World Cup 2026 Schedule - Aruba Time</h1></div><div class="timepill">AST / UTC-4</div></header><div class="layout"><section class="groups"><div class="section-title"><span></span><h2>Group Stage</h2></div><div class="group-grid">${groupCards}</div></section><section class="knockout"><div class="section-title"><span></span><h2>Knockout Stage</h2></div><div class="bracket">${bracket}</div></section></div><footer><b>Legend</b> AST = Atlantic Standard Time (UTC-4) · 1A/2A = group finish · 3A* = possible third-place qualifier · W = winner · L = loser · Source: ${esc(matches[0]?.sourceVersion ?? 'source schedule')}</footer></main></body></html>`;
}
function renderGroupHtml(g:string,i:number,matches:Match[],teams:Team[]) { const ms=matches.filter(m=>m.group===g); const ts=teams.filter(t=>t.group===g); return `<article class="group-card" style="--accent:${colors[i]}"><div class="group-head"><h3>Group ${g}</h3><div>${ts.map(t=>`<span>${esc(t.code)}</span>`).join('')}</div></div><div class="teams">${ts.map(t=>`<p><b>${esc(t.code)}</b> ${esc(t.name)}</p>`).join('')}</div><div class="matches">${ms.map(m=>`<div class="match"><div class="meta">M${m.matchNo} · ${esc(m.dateAst)} · ${m.displayTime}</div><div class="fixture"><b>${esc(teamLabel(m,1))}</b><span>${m.score ? esc(m.score) : 'v'}</span><b>${esc(teamLabel(m,2))}</b></div><div class="names">${esc(teamName(m,1))} / ${esc(teamName(m,2))}</div><div class="venue">${esc(m.venue)}, ${esc(m.city)}</div></div>`).join('')}</div></article>`; }
function renderKoHtml(m:Match) { return `<div class="ko-card"><div class="meta">M${m.matchNo} · ${esc(m.dateAst)} · ${m.displayTime}</div><div class="fixture"><b>${esc(teamLabel(m,1))}</b><span>v</span><b>${esc(teamLabel(m,2))}</b></div><div class="venue">${esc(m.venue)}, ${esc(m.city)}</div></div>`; }
function css() { return `*{box-sizing:border-box}body{margin:0;background:#06111f;color:#fff;font-family:Inter,Arial,sans-serif}.poster{width:3840px;height:2160px;padding:54px 64px;background:radial-gradient(circle at 16% 0%,#183b66 0,#081827 34%,#040b14 100%);overflow:hidden}header{height:160px;display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #27445f}h1{font-size:74px;line-height:1;margin:0;letter-spacing:-2px}.eyebrow{color:#67e8f9;text-transform:uppercase;font-weight:800;letter-spacing:7px;font-size:24px;margin:0 0 14px}.timepill{font-size:38px;font-weight:900;padding:22px 34px;border-radius:999px;background:linear-gradient(135deg,#06b6d4,#7c3aed);box-shadow:0 14px 50px #0008}.layout{display:grid;grid-template-columns:2440px 1fr;gap:44px;height:1810px;padding-top:30px}.section-title{display:flex;align-items:center;gap:16px;margin-bottom:18px}.section-title span{width:14px;height:46px;border-radius:9px;background:#22d3ee}.section-title h2{font-size:42px;margin:0}.group-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.group-card,.round{background:linear-gradient(180deg,#12243acc,#0b1727ee);border:1px solid #2c4a67;border-radius:24px;box-shadow:0 20px 50px #0008}.group-card{height:542px;padding:18px;border-top:7px solid var(--accent)}.group-head{display:flex;align-items:center;justify-content:space-between}.group-head h3{font-size:31px;margin:0}.group-head span{font-size:18px;font-weight:900;margin-left:6px;background:#fff;color:#06111f;border-radius:8px;padding:5px 7px}.teams{display:grid;grid-template-columns:1fr 1fr;gap:5px 12px;margin:11px 0 13px}.teams p{font-size:17px;margin:0;color:#cbd5e1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.match{border-radius:14px;background:#081827;border:1px solid #24425d;margin-top:7px;padding:7px 9px}.meta{font-size:16px;color:#67e8f9;font-weight:800}.fixture{display:grid;grid-template-columns:1fr 42px 1fr;align-items:center;gap:8px;font-size:21px;margin-top:3px}.fixture span{text-align:center;color:#fbbf24;font-weight:900}.fixture b:last-child{text-align:right}.names,.venue{font-size:14px;color:#94a3b8;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.knockout{min-width:0}.bracket{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;height:1708px}.round{padding:14px;display:flex;flex-direction:column;gap:8px}.round h3{font-size:25px;margin:0 0 3px;color:#f8fafc}.ko-card{background:#0b1727;border:1px solid #31516f;border-left:5px solid #f59e0b;border-radius:16px;padding:10px}.ko-card .fixture{font-size:20px}.ko-card .venue{font-size:13px;margin-top:3px}footer{height:76px;border-top:2px solid #27445f;color:#cbd5e1;font-size:24px;padding-top:20px}`; }

export function renderSvg(matches: Match[], teams: Team[]) {
  const lines = [`<text x="70" y="105" class="title">World Cup 2026 Schedule - Aruba Time</text>`, `<text x="3380" y="105" class="pill">AST / UTC-4</text>`];
  groups.forEach((g,i)=>{ const x=70+(i%4)*585,y=190+Math.floor(i/4)*525; lines.push(`<rect x="${x}" y="${y}" width="550" height="500" rx="22" class="panel"/><rect x="${x}" y="${y}" width="550" height="8" fill="${colors[i]}"/><text x="${x+20}" y="${y+44}" class="h2">Group ${g}</text>`); teams.filter(t=>t.group===g).forEach((t,j)=>lines.push(`<text x="${x+20}" y="${y+78+j*24}" class="team"><tspan class="code">${esc(t.code)}</tspan> ${esc(t.name)}</text>`)); matches.filter(m=>m.group===g).forEach((m,j)=>lines.push(`<text x="${x+20}" y="${y+184+j*47}" class="small">M${m.matchNo} ${esc(m.dateAst)} ${m.displayTime} ${esc(teamLabel(m,1))} ${m.score?esc(m.score):'v'} ${esc(teamLabel(m,2))}</text><text x="${x+20}" y="${y+207+j*47}" class="venue">${esc(m.venue)}, ${esc(m.city)}</text>`)); });
  lines.push(`<text x="2490" y="175" class="h2">Knockout Stage</text>`); ['Round of 32','Round of 16','Quarter-final','Semi-final','Bronze Final','Final'].forEach((stage,col)=>{ const ms=matches.filter(m=>m.stage===stage); const x=2490+col*220; lines.push(`<text x="${x}" y="230" class="round">${esc(stage)}</text>`); ms.forEach((m,j)=>{ const y=260+j*(stage==='Round of 32'?103:stage==='Round of 16'?190:300); lines.push(`<rect x="${x}" y="${y}" width="205" height="82" rx="13" class="ko"/><text x="${x+10}" y="${y+24}" class="small">M${m.matchNo} ${m.displayTime}</text><text x="${x+10}" y="${y+50}" class="small">${esc(teamLabel(m,1))} v ${esc(teamLabel(m,2))}</text><text x="${x+10}" y="${y+70}" class="venue">${esc(m.city)}</text>`); }); });
  lines.push(`<text x="70" y="2110" class="footer">Legend: AST = Atlantic Standard Time (UTC-4); 1A/2A = group finish; 3A* = possible third-place qualifier; W = winner; L = loser. Source: ${esc(matches[0]?.sourceVersion ?? '')}</text>`);
  return `<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" width="3840" height="2160" viewBox="0 0 3840 2160"><style>.title{font:800 72px Arial;fill:#fff}.pill{font:800 40px Arial;fill:#67e8f9}.h2{font:800 34px Arial;fill:#fff}.panel{fill:#102033;stroke:#2b4a66}.team{font:20px Arial;fill:#cbd5e1}.code{font-weight:800;fill:#fff}.small{font:19px Arial;fill:#e2e8f0}.venue{font:15px Arial;fill:#94a3b8}.round{font:800 24px Arial;fill:#fbbf24}.ko{fill:#0b1727;stroke:#31516f}.footer{font:24px Arial;fill:#cbd5e1}</style><rect width="3840" height="2160" fill="#06111f"/><circle cx="500" cy="-120" r="900" fill="#183b66" opacity=".8"/>${lines.join('')}</svg>`;
}
